name: Preview site

on:
  push:
    branches-ignore:
      - master

jobs:
  preview:
    name: Build & deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build:themed

      - name: Deploy to surge
        run: pnpm deploy-preview -d playroom--${GITHUB_SHA}.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Update PR status
        run: pnpm post-commit-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
